- Project.toml
This should fix the problem @sudomaze  had in issue #13 .
It's resolved but for others it might exist and using v2.0.0 should be fine as well as tested by @TheCedarPrince
> Luxor 2 should be fine.

- .github/workflows/ci.yml
- src/Javis.jl
> give a better error message if tex2svg fails

- src/Javis.jl
- test/animations.jl
> Use Transition with a single argument

- README.md
What do you think @TheCedarPrince ?
> Link to my blog post and removed stable for now

- src/Javis.jl
- src/morphs.jl
- src/svg2luxor.jl
- test/animations.jl
- test/runtests.jl
- test/unit.jl
> support for :same and Rel as frames

- src/Javis.jl
- test/animations.jl
> able to return a Point

- Project.toml
- src/Javis.jl
- test/animations.jl
- test/unit.jl
Fix #53 
This should remove the necessity to install FFMPEG which might be a pain for Windows users.
> using FFMPEG

- Project.toml
- src/Javis.jl
- test/animations.jl
better defaults as described in #57
> Reasonable defaults

- src/Javis.jl
- test/unit.jl
> Bugfix for short-hand rotation

- src/Javis.jl
- test/runtests.jl
Implements #70 -- let me know if there is anything else you want to tweak from this!
> Auto export of Luxor functions

- docs/src/tutorials/tutorial_1.md
- src/Javis.jl
- src/backgrounds.jl
Fixed some link bugs in the documentation.
> fixed some links and refs

- README.md
- contributing.md
- docs/make.jl
- docs/src/contributing.md
- docs/src/index.md
- docs/src/mission.md
- docs/src/tutorials.md
Documentation improvements across the `Javis.jl` ecosystem.
> General docs improvements

- CHANGELOG.md
- Project.toml
I think it's nice to have a changelog besides the automatic one given in the tags page.
> Changelog v0.1.1

- .github/workflows/format_check.yml
- CHANGELOG.md
- docs/make.jl
- src/Javis.jl
- src/backgrounds.jl
- src/luxor_overrides.jl
- src/morphs.jl
- src/subaction_animations.jl
- src/svg2luxor.jl
- src/util.jl
- test/animations.jl
- test/svg.jl
- test/unit.jl
#123 
I ran `JuliaFormatter.jl`'s `format(".")` function to recursively format each file to show how the formatting looks like. Though this PR would not fix everything for making a GitHub Action, it will allow a point for each piece of code to be formatted via JuliaFormatter from which we could make a GitHub Action.
Further, each piece of our code from this point forward could be in compliance with JuliaFormatter. 
What do you think @Wikunia ?
> Applied JuliaFormatter to all of Javis.jl files

- src/Javis.jl
- I don't think it's necessary :smile: 
There is no issue for this. @TheCedarPrince just saw this in his stream :wink: 
I've removed `create_gif` from the docstring of the `javis` function.
> removed create_gif from docstring

- docs/src/index.md
- docs/src/tutorials.md
- docs/src/tutorials/tutorial_1.md
- docs/src/tutorials/tutorial_2.md
This PR fixes links in our documentation. If merged we should also merge master again into v0.2
> fixing links in documentation

- docs/make.jl
- docs/src/howto.md
- docs/src/tutorials/tutorial_3.md
- docs/src/tutorials/tutorial_4.md
- src/subaction_animations.jl
They are basically not relevant for documentation PRs I think :wink: 
Closes #128 
I've started with a `howto.md` where I've answered all the questions which are mentioned in the issue. We probably want to add more. Hope the general format makes sense.
> [WIP] First version of How To

- docs/src/tutorials/tutorial_1.md
> Fix minor typos in tuto 1

- docs/src/tutorials.md
> Added tutorial 5 to Tutorial Index

- docs/make.jl
Push preview for docs! That's all this is :100:
> Wik documentation push preview

- src/Javis.jl
- test/unit.jl
Closes #152
I used the `ErrorException` message to raise a message to the user about defining a `Video` before an `Action` object.
> Improved Action Error Msg

- test/runtests.jl
- test/unit.jl
I created a small subroutine to run before the test suite to remove any files stored in `test/images/` that were not designated for exclusion.
> Remove any files stored in test/images

- CHANGELOG.md
- Project.toml
I changed some compat entries for GtkReactive and Cairo as I don't assume that Javis is that much effective and using the caret specifier is normally the right thing to do.
> Changed compat entries to allow more

- docs/src/contributing.md
- docs/src/mission.md
- docs/src/tutorials/tutorial_1.md
- docs/src/tutorials/tutorial_2.md
- docs/src/tutorials/tutorial_3.md
- docs/src/tutorials/tutorial_5.md
- docs/src/tutorials/tutorial_6.md
I explained some things in more detail like what options one have to create an `Action` and how `Scaling` works in the background. In general we should aim to explain more in tutorials instead of just making animations. Currently I find it quite hard to read the tutorials and get the information I need. Hopefully this PR will fix some of those issues.
> Tutorial overhaul

- README.md
Just some small changes to the readme for v0.2
> Updated readme to v0.2

- docs/src/howto.md
You may need to install a plugin like https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2 if you use VSCode. 😁
> Add the missing bracket

- README.md
This PR just adds additional recognition for some new contributors and adds links to users' GitHub profiles.
> Updated README for contributing section

- CHANGELOG.md
- docs/src/tutorials/tutorial_1.md
- src/Javis.jl
- src/action_animations.jl
- src/latex.jl
- src/morphs.jl
- src/structs/Action.jl
- src/structs/Object.jl
- src/structs/Rel.jl
- src/util.jl
- test/animations.jl
- test/svg.jl
- test/unit.jl
- test/viewer.jl
Closes #248 
I ran `sed -i -- 's/BackgroundObject/Background/g' **/*(D.)` in the directory of Javis to change occurrences of `BackgroundObject` to `Background`.
> Change BackgroundObject to Background

- docs/src/tutorials/tutorial_6.md
Closes #259 
I've changed all code blocks and removed the  parts that referred to the array structure or special things like list comprehension.
> Tutorial 6 for v0.3

- CHANGELOG.md
- Project.toml
- docs/src/howto.md
- docs/src/tutorials.md
- docs/src/tutorials/tutorial_4.md
- src/morphs.jl
- src/object_values.jl
- src/structs/Object.jl
- src/structs/ObjectSetting.jl
Closes #270 
@Wikunia can you check the docstrings and reference issues? I don't see anything else incorrect currently!
> Final check v0.3

- README.md
Adding recognition for ArbitRandomUser's contribution to cleaning up the Javis code base!
> Recognized ArbitRandomUser

- .github/workflows/TagBot.yml
Followed this https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249 to create a new release tag when we register a new release. This will make tagging a release on GitHub almost instant as it doesn't use cron jobs anymore.
> Tagbot using issue instead of cron

- docs/src/tutorials/tutorial_1.md
Closes #296 
I've now explained `O` but I can also change it to `Point(0,0)` if it's still confusing.
Maybe you, @agerlach, want to check whether it is more readable now.
> explanation of origin O

- CHANGELOG.md
- src/Javis.jl
- test/animations.jl
Closes #299 
I've changed the color palette which produces better results for me. Maybe you can test the example from #299 before and after @TheCedarPrince
> bugfix color palette

- CHANGELOG.md
- Project.toml
- src/latex.jl
- test/svg.jl
Closes #306
Check if `$` in the LaTeXString before removing.
> Latex $$ fix

- README.md
Just a quick PR to add in new contributors and also improved info about our developer community.
> Added new contributors and updated README

- docs/src/tutorials/tutorial_1.md
Added new line to separate the segments.
> Added new line

- docs/src/tutorials/tutorial_3.md
Update relevant portions of the tutorials for #277
> Update docs for latex alignment

- README.md
Closes #
The readme was horribly out of date - that is fixed now!
> Updated the README to something more recent :tada:

- examples/cosmic_dance.jl
Closes #358 
Thanks @Sov-trotter for pointing out the mistake.
> fixed cosmic_dance.jl example

- src/action_animations.jl
- Shall I for fixing the doctsing?
Closes #354
Using `anim_translate` instead of `Translation` in the docstring for `translate()`
> updated translate docstring

- CHANGELOG.md
- Project.toml
Tagging a new release of Javis for folks to use convenience methods!
> Bumping Javis to v0.6.1 for Release :tada: 

- README.md
Closes #391 
Added @rmsrosa to the contributors section
> added rmsrosa to the contributors section

- CHANGELOG.md
- src/latex.jl
Closes #384 #420 
Replace `tex2svg $ts` with `cmd /C tex2svg $ts` because:
"On Windows, many similar commands, such as echo and dir, are not external programs and instead are built into the shell cmd.exe itself. One option to run these commands is to invoke cmd.exe, for example cmd /C echo hello."
Quote from https://docs.julialang.org/en/v1/manual/running-external-programs/#Running-External-Programs
> fix latex in windows

- src/scales.jl
- test/animations.jl
This should go into v0.7.1 as a fix of a previously merged feature #412 
Will add some more tests later...
> @scale_layer macro with correct scale and translate

- .github/workflows/ci.yml
Run CI on the new Julia v1.7 instead of v1.6
> ci on Julia v1.7

- docs/src/tutorials/tutorial_8.md
N/A
This was a typo in the code section. I simply fixed it to be the same as the final code that was given at the end,
The map should be over `final_points` and not `planets` since we're making animations using the pre-defined points. This led to a cryptic error while following the tutorial.
> Fixed collection used to make animation points in tutorial 8

- src/latex.jl
Small bugfix of the method introduced in #475 . The method overwrote a latex method from before. This PR combines the two
> fix overwritten latex function

- README.md
- docs/make.jl
The edit on github link now points to main instead of master
> master to main for readme and docs
