- src/Javis.jl
I am going to go ahead and merge this as I only added documentation for the `latex` function and cleaned up its syntax. Also, ran tests on it and everything based so in full compliance with the rest of the codebase.
> Created documentation for latex function in compliance with BlueStyle

- docs/src/references.md
- src/Javis.jl
Might solve some of #17 
1. Added some docstrings to public types and functions
2. The reference in the docs is now split to public and private
> General documentation

- src/Javis.jl
- test/animations.jl
- test/unit.jl
As discussed in #33 we decided to revert `Translation(p)` which mapped to `Translation(p, p)` and now map it to `Translation(O, p)`
Additionally one can now write `Translation(x, y)` such that one does not need to write `Point` every time.
> Transition shorthand

- Project.toml
FFMPEG v0.3.0 should be good enough and otherwise Plots gets downgraded to a pre v1 version which is probably neither expected nor wanted. Plots.jl has fixed their bounds but hasn't released a new version yet.
> downgrade FFMPEG

- src/Javis.jl
- test/animations.jl
- test/unit.jl
Fix #68
It's now possible to write:
```
javis(video, [
Action(1:10, ground),
Action(:circ, (args...)->circ_ret_trans(p), Rotation(2π)),
Action((args...)->line(Point(-200, 0), Point(-200, -10*ang(:circ)), :stroke))
])
```
> Bugfix for allowing id as the first argument

- src/Javis.jl
This should fix the docstring of `latex` from issue #99
> Hotfix for latex docstring

- CHANGELOG.md
- Project.toml
- TODO.md
- src/Javis.jl
Reverts Wikunia/Javis.jl#133
This should get merged into the v0.2 branch instead.
> Revert "Progressmeter @showprogress"

- CHANGELOG.md
- src/Javis.jl
- src/util.jl
- test/unit.jl
- wasn't in Todo
Closes #146 
With this PR it's possible to not define frames for a SubAction -> all frames of the action are used.
Added two constructors for this and changed the input of `last_frames` for SubAction.
> Define SubAction on all frames

- CHANGELOG.md
- src/Javis.jl
- test/svg.jl
This removes the current deprecation warning for `latex(latexstring, 25)` where 25 is the fontsize. We don't support this anymore and we had the deprecation warning for v0.1.3 -> v0.1.5 so with v0.2 we don't want to keep this.
If you find this PR and want to know how to set the font size:
```
fontsize(20)
latex(latexstring)
```
is the way to go.
> removed possibility to set the fontsize inside the latex function

- docs/src/howto.md
A documentation PR :smile: 
Close #169 
I have addressed three questions:
- How can I show a text being drawn?
- How can I let an object move along a path?
- How can I see a live view of the animation?
> How To:  draw_text, follow_path and liveview

- CHANGELOG.md
- src/util.jl
- test/unit.jl
Closes #187
If `get_interpolation` is called with the last frame it returns 1.0 without any computation
> [Bugfix] return 1.0 in interpolation for single frame

- src/Javis.jl
None
Currently the `get_javis_frame` function would convert the frame to `ARGB32` and inside `javis` it would be converted to `RGB`. This is stupid :smile:  -> convert it directly to the image type we need.
> convert frame only once

- docs/src/tutorials/tutorial_1.md
> Tutorial 1 v0.3

- docs/src/howto.md
Closes #251 
I went through part of the HowTos and changed the code. Currently experiencing some weirdness with `follow_path`. If this turns out to be a bug I'll create an extra issue.
I just forgot to change the frame range :smile: We need better error messages/warnings :smile:
> HowTo v0.3

- src/Javis.jl
- src/util.jl
- test/unit.jl
#249 point 2
I check the length of the object that exists and compare whether the action is defined for a range outside of that frames.
The warning message tries to give the best clue possible by giving the number of the action and object and the frame range that it could be in vs the one it is in.
> Warning if action is defined out of object frames

- src/morphs.jl
> Fixed keyword in morph docstring and changed example with `do_action`

- .github/ISSUE_TEMPLATE/bug_report.md
- CHANGELOG.md
- Project.toml
- src/Javis.jl
I've added a kwarg `ffmpeg_loglevel` which defaults to `"panic"` as before but can be changed to `"info"` or some others.
Additionally I've added it to the issue template such that if ffmpeg fails we get more information.
The changelog and Project.toml are updated to release v0.3.2 when this is merged.
> kwarg: ffmpeg_loglevel

- .JuliaFormatter.toml
- CHANGELOG.md
- examples/follow_path.jl
- examples/fourier.jl
- examples/projection.jl
- src/Javis.jl
- src/Shape.jl
- src/structs/Frames.jl
- src/util.jl
- test/svg.jl
I'm not a fan of `always_use_return` therefore I disabled it. :wink: I think it makes sense to explicitly use `return` when one wishes to use the value afterwards which isn't the case for things like `sethue`.
> set always_use_return to false in formatter

- docs/src/tutorials/tutorial_2.md
No issues linked. (Since this is a minor change I left out creating an issue for it. If required will willingly do so.)
There seems to be a minor typo in Tutorial-2. The inner circle has a few wrong parameters. Corrected it using the examples from the rest of the tutorial. 
Thanks for the awesome package and the wonderful tutorials!
> Fix minor typo in tutorials

- src/action_animations.jl
- src/structs/Action.jl
Fixed articles from `a` to `an` for `Action` in `Action.jl` and `action_animation.jl`
> Fixed article in some places in docstrings

- CHANGELOG.md
- Project.toml
- docs/src/tutorials/tutorial_1.md
- test/morphing.jl
Closes #332
The problem was still that `O` can be confused with `0` easily. Now it should be very clear due to both the word `letter` as well as mentioning that it stands for `origin`.
> Tutorial update to clarify that we use the letter O

- docs/src/workflows.md
Some documentation fixes in the workflow section:
- Removed `:balloon:` which didn't render
- Made a section bold instead of screaming
- Comment out the Twitch section instead of using an HTML comment which doesn't work
> fixing some bugs in the workflow docs

- docs/src/howto.md
- docs/src/tutorials/tutorial_1.md
-  all above not necessary as it's a doc change
No issue for this just from the Zulip channel
I've updated the HowTo section by adding a 
```
How can I avoid ambiguity errors with Luxor.jl?
```
section.
Additionally I added two sentences to the first tutorial to make clear that `using Luxor` should be avoided inside `Javis` scripts.
> Luxor ambiguity clarification in howto and tutorial 1

- docs/src/tutorials/tutorial_1.md
I recently re-organized the documentation of Luxor (along `divio` lines) so any direct links you've made to individual sections of the Luxor docs, like the one in this PR, will probably 404.
Naturally I'm very sorry I've caused you extra work. :) But on the plus side, I probably won't reorganize them again for a while...
> Fix link to Luxor tutorial

- src/shorthands/JShape.jl
Fixed the docstring [here](https://github.com/Wikunia/Javis.jl/blob/4dd338c53d6df5784fda4703a64d4a89b2094a18/src/shorthands/JShape.jl#L16) which replaces `bgein...end` with `begin...end`
> Fix spelling error in JShape docstring

- src/layers.jl
The type annotation in documentation for `get_position` on `Layers` [here](https://wikunia.github.io/Javis.jl/dev/references/#Javis.get_position-Tuple{Javis.Layer}) is a duplicate of the one for `Object` [here](https://wikunia.github.io/Javis.jl/dev/references/#Javis.get_position-Tuple{Object}).
This PR just changes 1 line to show the correct type annotation in the documentation.
> Fix documentation for get_position on Layer

- src/layers.jl
some of the references in the layers docstrings were wrong. Mixed up whether it's a macro or not.
This is fixed now
> fix some layers refs

- src/shorthands/JCircle.jl
- src/shorthands/JEllipse.jl
Twice ```` `` ````  was in the docstrings to start an inline code "block" which I changed to ```` ` ````
> fix `` code in docstrings

- src/structs/Frames.jl
- test/animations.jl
- test/unit.jl
Closes #335 
When the first Action of an Object uses `RFrames` it will be ignored as it is unexpected to error of being outside the frame range.
> Ignore the RFrames for the first Action

- src/layers.jl
Closes #382 
This fixes some issues with the JLayers docstring. I started by fixing the example that is within the docstring itself. @Sov-trotter - feel free to add the rest of your changes here to address issue #382
> Updating `@JLayer` Docstring

- examples/fourier.jl
[https://github.com/JuliaAnimators/Javis.jl/issues/467](url)
Closes #460 
Updated the file with correct ones.
> Removal of error in Fourier example

- CHANGELOG.md
- src/latex.jl
- test/svg.jl
Closes #474.
After some discussion in the Javis.jl Zulip chat, I added an overload for the `latex` function with `valign` defaulting to `:top` and `halign` defaulting to `:left`.
A single regression test was added in `svg.jl` to make sure that this overload was working correctly.
> add LatexString overload, add test

- src/Javis.jl
small change ,
added wait for ffmpegproc (to exit) after we close it ,
Not a major issue but this ensures the .mp4 exists after render is done.
A problem arises if one is going to play the video or further do some other processing on it from the script immediately after render .
> Wait for ffmpeg to exit after close
